In [1]:
 ##Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

In [2]:
dataset = pd.read_csv('hiring.csv')
dataset.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

## First step of feature Engineering

In [3]:
dataset['experience'].fillna(0, inplace=True)

In [4]:
dataset.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          0                    8.0                           9      50000
1          0                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [7]:
dataset.isna().sum()

experience                    0
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [9]:
dataset['test_score(out of 10)'].fillna(dataset['test_score(out of 10)'].mean(), inplace=True)
dataset.isna().sum()

experience                    0
test_score(out of 10)         0
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [11]:
X = dataset.iloc[:, :3]

In [12]:
#Converting words to integer values
def convert_to_int(word):
    word_dict = {'one':1, 'two':2, 'three':3, 'four':4, 'five':5, 'six':6, 'seven':7, 'eight':8,
                'nine':9, 'ten':10, 'eleven':11, 'twelve':12, 'zero':0, 0: 0}
    return word_dict[word]

X['experience'] = X['experience'].apply(lambda x : convert_to_int(x))

y = dataset.iloc[:, -1]

In [13]:
#Splitting Training and Test Set
#Since we have a very small dataset, we will train our model with all availabe data.

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [14]:
#Fitting model with trainig data
regressor.fit(X, y)

LinearRegression()

In [15]:
# Saving model to disk
pickle.dump(regressor, open('model.pkl','wb'))

In [16]:
# Loading model to compare the results
model = pickle.load(open('model.pkl','rb'))
print(model.predict([[2, 9, 6]]))

[53290.89255945]


In [23]:
print(X.columns)
print(len(X.columns))
print("\n\n")
print(X['experience'].unique())
print(X['test_score(out of 10)'].unique())
print(X['interview_score(out of 10)'].unique())

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)'], dtype='object')
3



[ 0  5  2  7  3 10 11]
[ 8.          6.         10.          9.          7.          7.85714286]
[ 9  6  7 10  8]
